services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\Article\ArticleRepository:

    App\Domain\Model\Article\ArticleVersionRepository:
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['App\Domain\Model\Article\ArticleVersion']

    App\Application\Article\Command\CreateArticleHandler:
    App\Application\Article\Command\UpdateArticleHandler:
    App\Application\Article\Command\DeleteArticleHandler:
    App\Application\Article\Command\WorkflowCommandHandler:
    App\Application\Article\Command\AddAttachmentsHandler:
    App\Application\Article\Command\AddDocumentHandler:
    App\Application\Article\Command\AddImageHandler:

    App\Infrastructure\Article\Security\Voter\ArticleVoter:

    App\Infrastructure\Article\ParamConverter\ArticleParamConverter:
        tags:
            - { name: request.param_converter, converter: app.article }

    App\Infrastructure\Article\Form\ArticleTagType:

    App\Infrastructure\Article\Twig\ArticleExtension:
    App\Infrastructure\Article\Twig\ArticleRuntime:
        tags:
            - twig.runtime

    app.article.html_purifier_config:
        class: HTMLPurifier_Config
        factory: [App\Infrastructure\HTMLPurifier\Html5Config, create]
        arguments:
            $parent: '@exercise_html_purifier.config.default'
            $settings:
                HTML.Doctype: 'HTML 4.01 Transitional'
                HTML.Allowed: '*[class],div,strong,em,del,br,a[href],span,img[src],h1,blockquote,pre,ul,ol,li,figure,figcaption'

    app.article.html_purifier:
        class: HTMLPurifier
        arguments: ['@app.article.html_purifier_config']
        tags:
            - {name: exercise.html_purifier, profile: article}

