services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\Committee\CommitteeRepository:

    command_handlers:
        namespace: App\Application\Committee\Command\
        resource: '%kernel.project_dir%/src/Application/Committee/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.commands }

    App\Infrastructure\Committee\Security\Voter\CommitteeVoter:
    App\Infrastructure\Committee\Security\Voter\CommitteeMemberVoter:

    App\Infrastructure\Committee\ParamConverter\CommitteeParamConverter:
        tags:
            - { name: request.param_converter, converter: app.committee }
    App\Infrastructure\Committee\ParamConverter\CommitteeMemberParamConverter:
        tags:
            - { name: request.param_converter, converter: app.committee_member }

    App\Application\Committee\Validator\UniqueCommitteeTitleValidator:
