services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\Document\DocumentRepository:

    command_handlers:
        namespace: App\Application\Document\Command\
        resource: '%kernel.project_dir%/src/Application/Document/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.commands }

    App\Infrastructure\Document\Security\Voter\DocumentVoter:
    App\Infrastructure\Document\Security\Voter\DocumentVersionVoter:

    App\Infrastructure\Document\ParamConverter\DocumentParamConverter:
        tags:
            - { name: request.param_converter, converter: app.document }
    App\Infrastructure\Document\ParamConverter\DocumentVersionParamConverter:
        tags:
            - { name: request.param_converter, converter: app.document_version }

    App\Infrastructure\Document\Form\DocumentTagType:

    App\Application\Document\Validator\UniqueDocumentTitleValidator:
    App\Application\Document\Validator\UniqueDocumentVersionValidator:
