services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\Document\DocumentRepository:

    App\Application\Document\Command\CreateDocumentHandler:
    App\Application\Document\Command\UpdateDocumentHandler:
    App\Application\Document\Command\DeleteDocumentHandler:

    App\Application\Document\Command\CreateDocumentVersionHandler:
    App\Application\Document\Command\UpdateDocumentVersionHandler:
    App\Application\Document\Command\DeleteDocumentVersionHandler:

    App\Infrastructure\Document\Security\Voter\DocumentVoter:
    App\Infrastructure\Document\Security\Voter\DocumentVersionVoter:

    App\Infrastructure\Document\ParamConverter\DocumentParamConverter:
        tags:
            - { name: request.param_converter, converter: app.document }
    App\Infrastructure\Document\ParamConverter\DocumentVersionParamConverter:
        tags:
            - { name: request.param_converter, converter: app.document_version }

    App\Infrastructure\Document\Form\DocumentTagType:
