services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\Event\EventRepository:
    App\Domain\Model\Event\Venue\EventVenueRepository:
    App\Domain\Model\Event\Team\ParticipatingTeamRepository:
    App\Domain\Model\Event\Application\TitleEventApplicationRepository:

    command_handlers:
        namespace: App\Application\Event\Command\
        resource: '%kernel.project_dir%/src/Application/Event/Command/**/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.commands }

    application_command_handlers:
        namespace: App\Application\Event\Application\Command\
        resource: '%kernel.project_dir%/src/Application/Event/Application/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.commands }

    team_command_handlers:
        namespace: App\Application\Event\Team\Command\
        resource: '%kernel.project_dir%/src/Application/Event/Team/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.commands }

    venue_command_handlers:
        namespace: App\Application\Event\Venue\Command\
        resource: '%kernel.project_dir%/src/Application/Event/Venue/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.commands }

    App\Infrastructure\Event\Security\Voter\EventVoter:
    App\Infrastructure\Event\Security\Voter\TitleEventVoter:
    App\Infrastructure\Event\Security\Voter\TournamentVoter:
    App\Infrastructure\Event\Venue\Security\Voter\EventVenueVoter:

    App\Infrastructure\Event\ParamConverter\EventParamConverter:
        tags:
            - { name: request.param_converter, converter: app.event }
    App\Infrastructure\Event\Venue\ParamConverter\EventVenueParamConverter:
        tags:
            - { name: request.param_converter, converter: app.event_venue }
    App\Infrastructure\Event\Team\ParamConverter\ParticipatingTeamParamConverter:
        tags:
            - { name: request.param_converter, converter: app.event_team }
    App\Infrastructure\Event\Application\ParamConverter\TitleEventApplicationParamConverter:
        tags:
            - { name: request.param_converter, converter: app.event_application }

    App\Infrastructure\Event\Form\EventTagType:
    App\Infrastructure\Event\Form\TitleEventApplicationChoiceType:
    App\Infrastructure\Event\Form\VenueChoiceType:

    App\Application\Event\Application\Validator\UniqueApplicantClubNameValidator:
    App\Application\Event\Validator\UniqueEventNameValidator:
    App\Application\Event\Venue\Validator\UniqueEventVenueNameValidator:
    App\Application\Event\Team\Validator\UniqueParticipatingTeamNameValidator:
