services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\Event\Game\GameRepository:

    App\Application\Event\Game\Command\CreateGameHandler:
    App\Application\Event\Game\Command\UpdateGameHandler:
    App\Application\Event\Game\Command\DeleteGameHandler:
    App\Application\Event\Game\Command\ChangeFixtureHandler:
    App\Application\Event\Game\Command\RecordResultHandler:
    App\Application\Event\Game\Command\RescheduleGameHandler:
    App\Application\Event\Game\Command\UpdateScheduleTimeZoneHandler:

    App\Infrastructure\Event\Game\Security\Voter\GameVoter:

    App\Infrastructure\Event\Game\ParamConverter\GameParamConverter:
        tags:
            - { name: request.param_converter, converter: app.event_game }

    App\Infrastructure\Event\Game\Form\TeamChoiceType:
