services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\Event\EventRepository:
    App\Domain\Model\Event\EventVenueRepository:
    App\Domain\Model\Event\ParticipatingTeamRepository:
    App\Domain\Model\Event\Application\TitleEventApplicationRepository:

    App\Application\Event\Command\CreateEuropeanChampionshipHandler:
    App\Application\Event\Command\UpdateEuropeanChampionshipHandler:
    App\Application\Event\Command\CreateEuropeanCupHandler:
    App\Application\Event\Command\UpdateEuropeanCupHandler:
    App\Application\Event\Command\CreateTournamentHandler:
    App\Application\Event\Command\UpdateTournamentHandler:
    App\Application\Event\Command\DeleteEventHandler:

    App\Application\Event\Command\TransitionEventHandler:
    App\Application\Event\Command\AnnounceTitleEventHandler:
    App\Application\Event\Command\WithholdTitleEventHandler:
    App\Application\Event\Command\SanctionEventHandler:

    App\Application\Event\Command\CreateEventVenueHandler:
    App\Application\Event\Command\UpdateEventVenueHandler:
    App\Application\Event\Command\DeleteEventVenueHandler:

    App\Application\Event\Command\AddParticipatingTeamHandler:
    App\Application\Event\Command\UpdateParticipatingTeamHandler:
    App\Application\Event\Command\RemoveParticipatingTeamHandler:

    App\Application\Event\Application\Command\ApplyForTitleEventHandler:
    App\Application\Event\Application\Command\UpdateTitleEventApplicationHandler:
    App\Application\Event\Application\Command\WithdrawTitleEventApplicationHandler:

    App\Infrastructure\Event\Security\Voter\EventVoter:
    App\Infrastructure\Event\Security\Voter\TitleEventVoter:
    App\Infrastructure\Event\Security\Voter\TournamentVoter:
    App\Infrastructure\Event\Security\Voter\EventVenueVoter:

    App\Infrastructure\Event\ParamConverter\EventParamConverter:
        tags:
            - { name: request.param_converter, converter: app.event }
    App\Infrastructure\Event\ParamConverter\EventVenueParamConverter:
        tags:
            - { name: request.param_converter, converter: app.event_venue }
    App\Infrastructure\Event\ParamConverter\ParticipatingTeamParamConverter:
        tags:
            - { name: request.param_converter, converter: app.event_team }
    App\Infrastructure\Event\Application\ParamConverter\TitleEventApplicationParamConverter:
        tags:
            - { name: request.param_converter, converter: app.event_application }

    App\Infrastructure\Event\Form\EventTagType:
    App\Infrastructure\Event\Form\TitleEventApplicationChoiceType:
    App\Infrastructure\Event\Form\VenueChoiceType:

    App\Application\Event\Application\Validator\UniqueApplicantClubNameValidator:
    App\Application\Event\Validator\UniqueEventNameValidator:
    App\Application\Event\Validator\UniqueEventVenueNameValidator:
    App\Application\Event\Validator\UniqueParticipatingTeamNameValidator:
