services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\Event\Game\GameRepository:

    command_handlers:
        namespace: App\Application\Event\Game\Command\
        resource: '%kernel.project_dir%/src/Application/Event/Game/Command/*Handler.php'

    App\Infrastructure\Event\Game\Security\Voter\GameVoter:

    App\Infrastructure\Event\Game\ParamConverter\GameParamConverter:
        tags:
            - { name: request.param_converter, converter: app.event_game }

    App\Infrastructure\Event\Game\Form\TeamChoiceType:
