services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\File\FileRepository:

    App\Application\File\FileFactory:

    command_handlers:
        namespace: App\Application\File\Command\
        resource: '%kernel.project_dir%/src/Application/File/Command/*Handler.php'

    App\Application\File\ImagickResizer:
    App\Application\File\CachedResizer:
        decorates: App\Application\File\ImagickResizer

    App\Application\File\ImageResizer: '@App\Application\File\ImagickResizer'

    App\Infrastructure\File\FileUploader:

    App\Infrastructure\File\Twig\FileExtension:
