services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\File\FileRepository:

    App\Application\File\FileManager:

    App\Application\File\Command\AddFileHandler:
    App\Application\File\Command\RemoveFileHandler:
