services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\File\FileRepository:

    App\Application\File\FileManager:

    App\Application\File\Command\AddFileHandler:
    App\Application\File\Command\RemoveFileHandler:

    App\Application\File\ImagickResizer:
    App\Application\File\CachedResizer:
        decorates: App\Application\File\ImagickResizer

    App\Application\File\ImageResizer: '@App\Application\File\ImagickResizer'

    App\Infrastructure\File\FileUploader:
