services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\HallOfFame\HallOfFameRepository:

    command_handlers:
        namespace: App\Application\HallOfFame\Command\
        resource: '%kernel.project_dir%/src/Application/HallOfFame/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.commands }

    App\Infrastructure\HallOfFame\Security\Voter\HallOfFameEntryVoter:

    App\Infrastructure\HallOfFame\ParamConverter\HallOfFameEntryParamConverter:
        tags:
            - { name: request.param_converter, converter: app.hall_of_fame_entry }
