services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    doctrine.orm.messenger.middleware_factory.transaction:
        class: Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddlewareFactory
        arguments: ['@doctrine']

    messenger.middleware.doctrine_transaction:
        class: Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddleware
        factory: 'doctrine.orm.messenger.middleware_factory.transaction:createMiddleware'
        abstract: true
        arguments: ['default']
