services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\NationalGoverningBody\NationalGoverningBodyRepository:

    command_handlers:
        namespace: App\Application\NationalGoverningBody\Command\
        resource: '%kernel.project_dir%/src/Application/NationalGoverningBody/Command/*Handler.php'

    App\Infrastructure\NationalGoverningBody\Security\Voter\NationalGoverningBodyVoter:

    App\Infrastructure\NationalGoverningBody\ParamConverter\NationalGoverningBodyParamConverter:
        tags:
            - { name: request.param_converter, converter: app.national_governing_body }

    App\Application\NationalGoverningBody\Validator\UniqueNationalGoverningBodyValidator:
