services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\Staff\StaffMemberRepository:

    command_handlers:
        namespace: App\Application\Staff\Command\
        resource: '%kernel.project_dir%/src/Application/Staff/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.commands }

    App\Infrastructure\Staff\Security\Voter\StaffMemberVoter:

    App\Infrastructure\Staff\ParamConverter\StaffMemberParamConverter:
        tags:
            - { name: request.param_converter, converter: app.staff_member }

    App\Infrastructure\Staff\Form\StaffMemberRoleType:
