services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\User\UserRepository:

    command_handlers:
        namespace: App\Application\User\Command\
        resource: '%kernel.project_dir%/src/Application/User/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.commands }

    event_subscribers:
        namespace: App\Infrastructure\User\Event\
        resource: '%kernel.project_dir%/src/Infrastructure/User/Event/*Subscriber.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.events }

    App\Application\User\PasswordService:
        arguments:
            $passwordEncoder: '@app.user.password_encoder'

    App\Infrastructure\User\Security\Voter\UserVoter:

    App\Infrastructure\User\ParamConverter\UserParamConverter:
        tags:
            - { name: request.param_converter, converter: app.user }

    app.user.password_encoder:
        class: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface
        factory: ['@security.encoder_factory', 'getEncoder']
        arguments: ['App\Domain\Model\User\UserInterface']

    App\Application\User\Validator\UniqueEmailValidator:
