services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\Model\User\UserRepository:

    App\Application\User\Command\CreateUserHandler:
    App\Application\User\Command\CreateConfirmedUserHandler:
    App\Application\User\Command\UpdateUserHandler:
    App\Application\User\Command\DeleteUserHandler:

    App\Application\User\Command\ConfirmUserHandler:
    App\Application\User\Command\UnconfirmUserHandler:
    App\Application\User\Command\ChangePasswordHandler:
    App\Application\User\Command\RequestPasswordResetHandler:
    App\Application\User\Command\ResetPasswordHandler:
    App\Application\User\Command\SetPasswordHandler:

    App\Application\User\PasswordService:
        arguments:
            $passwordEncoder: '@app.user.password_encoder'

    App\Infrastructure\User\Security\Voter\UserVoter:

    App\Infrastructure\User\ParamConverter\UserParamConverter:
        tags:
            - { name: request.param_converter, converter: app.user }

    app.user.password_encoder:
        class: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface
        factory: 'security.encoder_factory:getEncoder'
        arguments: ['App\Domain\Model\User\UserInterface']

    App\Application\User\Validator\UniqueEmailValidator:
