parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '8.0'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        override_url: true
        url: '%env(resolve:DATABASE_URL)%'
        schema_filter: /^(?!rememberme_token|login_tokens)/
        types:
            datetime_utc: App\Doctrine\DBAL\Types\UtcDateTimeType
            timezone: App\Doctrine\DBAL\Types\TimezoneType
        mapping_types:
            datetime_utc: datetime
            timezone: string
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Model'
                prefix: 'App\Domain\Model'
                alias: App
