# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%locale%'
    csrf_protection: true
    http_method_override: false

    fragments:
        enabled: true

    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: session.handler.native_file
        name: IISHF_SESSION
        cookie_secure: true
        cookie_httponly: true
        cookie_samesite: lax
        gc_probability: 1
        gc_divisor: 100
        gc_maxlifetime: 1440

    #esi: true
    #fragments: true
    php_errors:
        log: true
