framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%locale%'
    csrf_protection: true
    http_method_override: false

    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

    session:
        handler_id: session.handler.native_file
        name: IISHF_SESSION
        cookie_secure: true
        cookie_httponly: true
        cookie_samesite: lax
        gc_probability: 1
        gc_divisor: 100
        gc_maxlifetime: 1440

    #esi: true
    #fragments: true
    php_errors:
        log: true
