framework:
    messenger:
        transports:
        # Uncomment the following line to enable a transport named "amqp"
        # amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
        # Route your messages to the transports
        # 'App\Message\YourMessage': amqp

        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands:
                middleware:
                    - messenger.middleware.validation
                    - messenger.middleware.doctrine_transaction
            messenger.bus.events:
                default_middleware: allow_no_handlers
                middleware:
                    - messenger.middleware.validation

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Infrastructure\Command\HandlesRecordedEventsMiddleware:
        arguments:
            $eventBus: '@messenger.bus.events'
    App\Application\Common\Command\EventRecorder:
    App\Application\Common\Command\EventRecorderInterface: '@App\Application\Common\Command\EventRecorder'
    App\Application\Common\Command\RecordsEvents: '@App\Application\Common\Command\EventRecorder'
