framework:
    messenger:
        transports:
        # Uncomment the following line to enable a transport named "amqp"
        # amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
        # Route your messages to the transports
        # 'App\Message\YourMessage': amqp

        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands:
                middleware:
                    - messenger.middleware.validation
                    - messenger.middleware.doctrine_transaction
            messenger.bus.events: ~

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    doctrine.orm.messenger.middleware_factory.transaction:
        class: Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddlewareFactory
        arguments: ['@doctrine']

    messenger.middleware.doctrine_transaction:
        class: Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddleware
        factory: 'doctrine.orm.messenger.middleware_factory.transaction:createMiddleware'
        abstract: true
        arguments: ['default']
