twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'form_fields.html.twig' ]
    date:
        format: !php/const DateTimeInterface::W3C
        timezone: UTC
    globals:
        google_recaptcha_key: '%env(GOOGLE_RECAPTCHA_KEY)%'
        facebook_app_id: '%env(FACEBOOK_APP_ID)%'
