framework:
    workflows:
        article_publishing:
            type: 'workflow'
            audit_trail: true
            marking_store:
                type: 'single_state'
                arguments:
                    - 'currentState'
            supports:
                - App\Domain\Model\Article\Article
            metadata:
                title: Article Publishing Workflow
            initial_place: draft
            places:
                draft:
                    metadata:
                        name: Draft
                review:
                    metadata:
                        name: Review
                published:
                    metadata:
                        name: Published
            transitions:
                submit:
                    guard: 'is_granted("ARTICLE_SUBMIT", subject)'
                    from: draft
                    to: review
                    metadata:
                        color: primary
                        button: Submit
                        confirm: Do you really want to submit the article for review?
                        confirm_btn: Submit article for review
                        success_message: The article has been submitted for review.
                reject:
                    guard: 'is_granted("ARTICLE_REVIEW", subject)'
                    from: review
                    to: draft
                    metadata:
                        color: warning
                        button: Reject
                        confirm: Do you really want to reject the article?
                        confirm_btn: Reject article
                        success_message: The article has been rejected.
                publish:
                    guard: 'is_granted("ARTICLE_REVIEW", subject)'
                    from: review
                    to: published
                    metadata:
                        color: success
                        button: Publish
                        confirm: When do you want to publish the article?
                        confirm_btn: Publish article
                        form_type: App\Infrastructure\Article\Form\PublishArticleType
                        success_message: The article has been published.
                unpublish:
                    guard: 'is_granted("ARTICLE_REVIEW", subject)'
                    from: published
                    to: draft
                    metadata:
                        color: warning
                        button: Unpublish
                        confirm: Do you really want to unpublish the article?
                        confirm_btn: Unpublish article
                        success_message: The article has been unpublished.

        tournament_sanctioning:
            type: 'workflow'
            audit_trail: true
            marking_store:
                type: 'single_state'
                arguments:
                    - 'currentState'
            supports:
                - App\Domain\Model\Event\Tournament
            metadata:
                title: Tournament Sanctioning Workflow
            initial_place: planned
            places:
                planned:
                    metadata:
                        name: Planned
                sanctioned:
                    metadata:
                        name: Sanctioned
            transitions:
                sanction:
                    guard: 'is_granted("EVENT_SANCTION", subject)'
                    from: planned
                    to: sanctioned
                    metadata:
                        color: success
                        button: Sanction
                        confirm: Do you really want to sanction the tournament?
                        confirm_btn: Sanction tournament
                        form_type: App\Infrastructure\Event\Form\Workflow\SanctionEventType
                        success_message: The tournament has been sanctioned.
                unsanction:
                    guard: 'is_granted("EVENT_SANCTION", subject)'
                    from: sanctioned
                    to: planned
                    metadata:
                        color: warning
                        button: Unsanction
                        confirm: Do you really want to unsanction the tournament?
                        confirm_btn: Unsanction tournament
                        success_message: The tournament has been unsanctioned.

        title_event_sanctioning:
            type: 'workflow'
            audit_trail: true
            marking_store:
                type: 'single_state'
                arguments:
                    - 'currentState'
            supports:
                - App\Domain\Model\Event\TitleEvent
            metadata:
                title: Title Event Sanctioning Workflow
            initial_place: planned
            places:
                planned:
                    metadata:
                        name: Planned
                announced:
                    metadata:
                        name: Announced
                sanctioned:
                    metadata:
                        name: Sanctioned
            transitions:
                announce:
                    guard: 'is_granted("EVENT_ANNOUNCE", subject)'
                    from: planned
                    to: announced
                    metadata:
                        color: primary
                        button: Announce
                        confirm: Do you really want to announce the title event?
                        confirm_btn: Announce title event
                        form_type: App\Infrastructure\Event\Form\Workflow\AnnounceTitleEventType
                        success_message: The title event has been announced.
                withhold:
                    guard: 'is_granted("EVENT_ANNOUNCE", subject)'
                    from: announced
                    to: planned
                    metadata:
                        color: warning
                        button: Withhold
                        confirm: Do you really want to withhold the title event?
                        confirm_btn: Withhold title event
                        success_message: The title event has been withheld.
                sanction:
                    guard: 'is_granted("EVENT_SANCTION", subject)'
                    from: announced
                    to: sanctioned
                    metadata:
                        color: success
                        button: Sanction
                        confirm: Do you really want to sanction the title event?
                        confirm_btn: Sanction title event
                        form_type: App\Infrastructure\Event\Form\Workflow\SanctionEventType
                        success_message: The title event has been sanctioned.
                unsanction:
                    guard: 'is_granted("EVENT_SANCTION", subject)'
                    from: sanctioned
                    to: planned
                    metadata:
                        color: warning
                        button: Unsanction
                        confirm: Do you really want to unsanction the title event?
                        confirm_btn: Unsanction title event
                        success_message: The title event has been unsanctioned.
