ENV["VAGRANT_DEFAULT_PROVIDER"] = "virtualbox"

Vagrant.configure("2") do |config|
	config.vm.box = "bento/ubuntu-20.04"
	config.vm.hostname = "iishf.test"

	config.vm.network :forwarded_port, host: 4430, guest: 443
	config.vm.network :forwarded_port, host: 33060, guest: 3306

	config.vm.network :private_network, ip: "10.11.12.13", nic_type: "virtio"

	config.vm.synced_folder "../", "/var/www/iishf", :nfs => true

	config.vm.provider "virtualbox" do |v|
  		v.gui = false
  		v.name = "iishf_web"
  		v.default_nic_type = "virtio"
  		v.memory = 2048
  		v.cpus = 1
	end

	config.vm.provision :ansible do |ansible|
    	ansible.playbook = "playbook.yml"
    	ansible.limit = "all"
    	ansible.verbose = "vv"
    	ansible.extra_vars = { ansible_python_interpreter: "auto" }
  	end
end
