home:
    path: /
    controller: App\Controller\HomeController::index
    methods:  [GET]
about_sport:
    path: /about-sport
    controller: App\Controller\HomeController::aboutSport
    methods:  [GET]
calendar:
    path: /calendar
    controller: App\Controller\HomeController::calendar
    methods:  [GET]
cookie:
    path: /cookie
    controller: App\Controller\HomeController::cookie
    methods:  [GET]
imprint:
    path: /imprint
    controller: App\Controller\HomeController::imprint
    methods:  [GET]
photo:
    path: /photo
    controller: App\Controller\HomeController::photo
    methods:  [GET]
privacy:
    path: /privacy
    controller: App\Controller\HomeController::privacy
    methods:  [GET]
video:
    path: /video
    controller: App\Controller\HomeController::video
    methods:  [GET]
login:
    path: /login
    controller: App\Controller\HomeController::login
    methods:  [GET, POST]
login_magic:
    path: /login/magic
    controller: App\Controller\HomeController::loginMagic
    methods:  [POST]
login_magic_confirm:
    path: /login/magic/confirm
    controller: App\Controller\HomeController::loginMagicConfirm
    methods:  [GET]
login_magic_link:
    path: /login/magic/login
    methods:  [GET]
logout:
    path: /logout
    methods:  [GET]
