home:
    path: /
    controller: \App\Controller\HomeController::index
    methods:  [GET]
login:
    path: /login
    controller: \App\Controller\HomeController::login
    methods:  [GET, POST]
logout:
    path: /logout
    methods:  [GET]
change_password:
    path: /change-password
    controller: \App\Controller\HomeController::changePassword
    methods:  [GET, POST]
forgot_password:
    path: /forgot-password
    controller: \App\Controller\HomeController::forgotPassword
    methods:  [GET, POST]
reset_password:
    path: /reset-password
    controller: \App\Controller\HomeController::resetPassword
    methods:  [GET, POST]
