imports:
    - { resource: 'services/' }

babdev_pagerfanta:
    default_view: twig
    default_twig_template: '@BabDevPagerfanta/twitter_bootstrap4.html.twig'

parameters:
    locale: 'en'
    routing.uuid: '[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}'
    routing.slug: '[0-9a-z-]+'
    routing.sha1: '[0-9a-f]{40}'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Command\:
        resource: '../src/Command'
        tags: ['console.command']

    App\Infrastructure\Messaging\MailService:
        arguments:
            $defaultSender: {'noreply@iishf.com': 'iishf.com'}

    App\Infrastructure\Security\ReCaptchaClient:
        arguments:
            $reCaptchaSecret: '%env(GOOGLE_RECAPTCHA_SECRET)%'
        tags:
            - { name: monolog.logger, channel: app.security }

    App\Infrastructure\Form\DatePickerExtension:
        arguments:
            $locale: "%locale%"

    App\Infrastructure\Form\Select2Extension:

    App\Infrastructure\Form\TrixEditorType:

    App\Infrastructure\Twig\DateExtension:
    App\Infrastructure\Twig\EmailExtension:
    App\Infrastructure\Twig\EmailRuntime:
        tags:
            - twig.runtime
