services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    app.dev.validator.email:
        class: App\Infrastructure\Validator\DevelopmentEmailValidator
        decorates: validator.email
        arguments: ["@app.dev.validator.email.inner"]
        tags:
            - { name: 'validator.constraint_validator', alias: 'Symfony\Component\Validator\Constraints\EmailValidator' }
