# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

imports:
    - { resource: 'services/' }

babdev_pagerfanta:
    default_view: twig
    default_twig_template: '@BabDevPagerfanta/twitter_bootstrap4.html.twig'

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    routing.uuid: '[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}'
    routing.slug: '[0-9a-z-]+'
    routing.sha1: '[0-9a-f]{40}'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Command\:
        resource: '../src/Command'
        tags: ['console.command']

    App\Infrastructure\Messaging\MailService:
        arguments:
            $defaultSender: {'noreply@iishf.com': 'iishf.com'}

    App\Infrastructure\Security\ReCaptchaClient:
        arguments:
            $reCaptchaSecret: '%env(GOOGLE_RECAPTCHA_SECRET)%'
        tags:
            - { name: monolog.logger, channel: app.security }

    App\Infrastructure\Form\DatePickerExtension:
        arguments:
            $locale: "%locale%"

    App\Infrastructure\Form\Select2Extension:

    App\Infrastructure\Form\TrixEditorType:

    App\Infrastructure\Twig\DateExtension:
    App\Infrastructure\Twig\EmailExtension:
    App\Infrastructure\Twig\EmailRuntime:
        tags:
            - twig.runtime
