imports:
    - { resource: 'services/' }

white_october_pagerfanta:
    default_view: twitter_bootstrap4

parameters:
    locale: 'en'
    env(GOOGLE_RECAPTCHA_KEY): ''
    env(GOOGLE_RECAPTCHA_SECRET): ''
    routing.uuid: '[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Command\:
        resource: '../src/Command'
        tags: ['console.command']

    App\Infrastructure\Messaging\MailService:
        arguments:
            $defaultSender: {'noreply@iishf.com': 'iishf.com'}

    App\Infrastructure\Security\ReCaptchaClient:
        arguments:
            $reCaptchaSecret: '%env(GOOGLE_RECAPTCHA_SECRET)%'
            $debug: '%kernel.debug%'
        tags:
            - { name: monolog.logger, channel: app.security }
