imports:
    - { resource: 'services/' }

parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Command\:
        resource: '../src/Command'
        tags: ['console.command']

    App\Infrastructure\Messaging\MailService:
        arguments:
            $defaultSender: {'noreply@iishf.com': 'iishf.com'}
