name: PHP Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: iishf
          MYSQL_DATABASE: iishf
          MYSQL_USER: iishf
          MYSQL_PASSWORD: iishf
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: curl, xdebug, sqlite3, json, intl, mbstring, imagick, bcmath, gmp, apcu, zip, mysql
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Validate composer.json and composer.lock
        run: composer validate --no-interaction --no-check-all --strict
      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run test suite
        run: vendor/bin/phpunit -c phpunit.xml.dist --coverage-text
        env:
          DATABASE_URL: mysql://iishf:iishf@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/iishf
          MAILER_DSN: null://null
