name: IISHF Web2019 CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: iishf
          MYSQL_DATABASE: iishf
          MYSQL_USER: iishf
          MYSQL_PASSWORD: iishf
        ports:
          - 3306
        volumes:
          - ./.github/workflow/mysql.cnf:/etc/mysql/conf.d/iishf.cnf
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            php-curl \
            php-xdebug \
            php-sqlite3 \
            php-json \
            php-intl \
            php-mbstring \
            php-imagick \
            php-bcmath \
            php-gmp \
            php-apcu \
            php-zip \
            php-mysql

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-all --strict

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run test suite
        run: vendor/bin/phpunit -c phpunit.xml.dist bin/phpunit --coverage-text
        env:
          DATABASE_URL: mysql://iishf:iishf@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/iishf
          MAILER_URL: null://localhost
